cipherText = ""
solution = "CRYPTOGRAPHY IS ALSO FASCINATING BECAUSE OF ITS GAME LIKE ADVERSARIAL NATURE A GOOD CRYPTOGRAPHER RAPIDLY" \
           "CHANGES SIDES BACK AND FORTH IN HIS OR HER THINKING FROM ATTACKER TO DEFENDER AND BACK JUST AS IN A GAME " \
           "OF CHESS SEQUENCES OF MOVES AND COUNTER MOVES MUST BE CONSIDERED UNTIL THE CURRENT SITUATION IS" \
           "UNDERSTOOD UNLIKE CHESS PLAYERS CRYPTOGRAPHERS MUST ALSO CONSIDER ALL THE WAYS AN ADVERSARY MIGHT TRY TO " \
           "GAIN BY BREAKING THE RULES OR VIOLATING EXPECTATIONS DOES IT MATTER IF SHE MEASURES HOW LONG I AM" \
           "COMPUTING DOES IT MATTER IF HER RANDOM NUMBER ISNT ONE"
